apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveryms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deliveryms
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: deliveryms
    spec:
      containers:
        - name: deliveryms-app
          image: tharindub/deliveryms:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
