name: Build and deploy

on:
  push:
    branches:
      - main

env:
  DEPLOYMENT_NAME: deliveryms

jobs:
  setup-build-publish:
    name: Setup-build-publish
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build started "

      - name: Checkout repository
        uses: actions/checkout@v3
      - run: echo "Project repository has been clonde to runnner(ubuntu)"

      #Create .env file
      - name: Create environmental vataible file
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: ".env"
          FILE_DATA: ${{ secrets.ENV_FILE }}

      #Login to docker  hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #Build and push dockerhub
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{env.DEPLOYMENT_NAME}}:${{ github.sha }}
